<a href="https://colab.research.google.com/github/juanfran18gc-code/jfMIAAD/blob/02-Semana/Practica4_261554.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Práctica #4 - Unidad 1. Manipulación de matrices
Crea dos matrices de 3x3 con números aleatorios entre 1 y 10. Realiza las siguientes operaciones:

1.  Suma ambas matrices.
2.  Resta la segunda matriz de la primera.
3.  Multiplica la primera matriz por 2.
4.  Realiza una multiplicación matricial entre las dos matrices.



In [9]:
import numpy as np

print("Matrices de 3X3 con numeros aleatorios entre 1 y 10")
#Agregamos una semilla 2 para generar los mismos numeros aleatorios de A - reproducibilidad
np.random.seed(2)

#Generamos dos matrices de números aleatorios entre 1 y 10
A = np.random.randint(1,11,(3,3))

#Agregamos una semilla 3 para generar los mismos numeros aleatorios de B - reproducibilidad
np.random.seed(3)
B = np.random.randint(1,11,(3,3))
#Imprimimos las matrices generadas
print(A)
print(B)
#Obtenemos la suma de matrices
print("Suma de A + B: ", A + B)

#Obtenemos la resta de matrices
print("Resta de B - A: ", B - A)

#Obtenemos el producto de A * 2
print("Producto de A * 2: ", A * 2)

#Obtenemos la multiplicación matricial con np.dot
print("Multiplicación matricial de A y B: ", np.dot(A,B))


Matrices de 3X3 con numeros aleatorios entre 1 y 10
[[9 9 7]
 [3 9 8]
 [3 2 6]]
[[ 9 10  4]
 [ 9  9  1]
 [ 6  4 10]]
Suma de A + B:  [[18 19 11]
 [12 18  9]
 [ 9  6 16]]
Resta de B - A:  [[ 0  1 -3]
 [ 6  0 -7]
 [ 3  2  4]]
Producto de A * 2:  [[18 18 14]
 [ 6 18 16]
 [ 6  4 12]]
Multiplicación matricial de A y B:  [[204 199 115]
 [156 143 101]
 [ 81  72  74]]
